name: Sync Incident to Project

on:
  issues:
    types: [opened, edited]

jobs:
  add-to-project:
    # Only run if the issue has the incident label
    if: contains(github.event.issue.labels.*.name, 'incident')
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract product from issue body
        id: extract-product
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            console.log('Issue body:', issueBody);
            
            // Parse the issue body to find the Product field
            const productMatch = issueBody.match(/### Product Affected\s*\n\s*(.+)/);
            
            if (!productMatch) {
              console.log('No product found in issue body');
              return '';
            }
            
            const product = productMatch[1].trim();
            console.log('Extracted product:', product);
            
            return product;
          result-encoding: string
      
      - name: Close issue if placeholder selected
        if: steps.extract-product.outputs.result == '-- Select a product --'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '⚠️ This issue was automatically closed because a valid product was not selected.\n\nPlease create a new issue and select a product from the dropdown menu.'
            });
            
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed',
              state_reason: 'not_planned'
            });
            
            core.setFailed('Issue closed: placeholder product selected');
      
      - name: Verify valid product selected
        if: |
          steps.extract-product.outputs.result != '-- Select a product --' &&
          steps.extract-product.outputs.result != ''
        run: echo "Valid product selected, continuing..."
      
      - name: Add issue to organization project
        id: add-to-project
        uses: actions/add-to-project@v0.5.0
        with:
          # Replace with your actual project URL
          # Example: https://github.com/orgs/YOUR-ORG/projects/1
          project-url: https://github.com/orgs/YOUR-ORG/projects/YOUR-PROJECT-NUMBER
          github-token: ${{ secrets.PROJECT_TOKEN }}
      
      - name: Set product field in project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const product = '${{ steps.extract-product.outputs.result }}';
            const itemId = '${{ steps.add-to-project.outputs.itemId }}';
            
            if (!product) {
              console.log('No product to set');
              return;
            }
            
            console.log(`Setting product "${product}" for item ${itemId}`);
            
            // GraphQL mutation to update the project field
            // You'll need to replace PROJECT_ID and FIELD_ID with your actual values
            const mutation = `
              mutation UpdateProjectField($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: $value
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;
            
            // Note: You'll need to get these IDs from your project
            // See setup instructions for how to find them
            const projectId = 'YOUR_PROJECT_ID';
            const fieldId = 'YOUR_PRODUCT_FIELD_ID';
            
            // Map product names to field option IDs
            const productOptions = {
              'MyApp': 'MYAPP_OPTION_ID',
              'ServiceApp': 'SERVICEAPP_OPTION_ID'
            };
            
            const optionId = productOptions[product];
            
            if (!optionId) {
              console.log(`Unknown product: ${product}`);
              return;
            }
            
            try {
              await github.graphql(mutation, {
                projectId: projectId,
                itemId: itemId,
                fieldId: fieldId,
                value: {
                  singleSelectOptionId: optionId
                }
              });
              console.log('Successfully set product field');
            } catch (error) {
              console.error('Error setting product field:', error);
              throw error;
            }
